# Generated by Django 4.2.16 on 2025-02-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='data',
            new_name='date',
        ),
    ]
