# Generated by Django 4.2.16 on 2025-02-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_data_buy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
