# Generated by Django 5.1.5 on 2025-02-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
