# Generated by Django 5.1.6 on 2025-02-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_dis_product_description_remove_product_pro_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_id',
            field=models.CharField(default='7', max_length=100),
            preserve_default=False,
        ),
    ]
