# Generated by Django 5.1.6 on 2025-02-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_pro_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='dis',
        ),
    ]
