# Generated by Django 3.2.12 on 2025-02-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_description_product_dis'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
